# Generated by Django 2.2.5 on 2020-01-23 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.AddField(
            model_name='chat',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chat',
            name='slug',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='chat',
            name='title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Chat'),
            preserve_default=False,
        ),
    ]
