# Generated by Django 2.2.5 on 2019-10-20 22:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics/')),
                ('bio', models.CharField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('travel_style', models.CharField(choices=[('FOODIE', 'Foodie'), ('LUX', 'Lux'), ('BUDGET', 'Budget'), ('SOLO', 'Solo'), ('HOTEL', 'Hotel'), ('FAMILY', 'Family'), ('WORK', 'Work')], max_length=20)),
                ('glter', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('facebook_url', models.CharField(max_length=150)),
                ('home_airport', models.CharField(max_length=3)),
                ('age_bracket', models.CharField(choices=[('UNDER 12', 'Under 12 years old'), ('12-17', '12-17 years old'), ('18-24', '18-24 years old'), ('25-34', '25-34 years old'), ('35-44', '35-44 years old'), ('45-54', '45-54 years old'), ('55-64', '55-64 years old'), ('65-74', '65-74 years old'), ('OVER 75', '75 years or older')], max_length=20)),
                ('int_travel', models.CharField(choices=[('1 OR LESS', 'One trip or less'), ('1 TO 3', '1-3 trips'), ('4 TO 8', '4-8 trips'), ('8 TO 12', '8-12 trips'), ('12 OR MORE', '12 or more trips')], max_length=20)),
                ('dom_travel', models.CharField(choices=[('1 OR LESS', 'One trip or less'), ('1 TO 3', '1-3 trips'), ('4 TO 8', '4-8 trips'), ('8 TO 12', '8-12 trips'), ('12 OR MORE', '12 or more trips')], max_length=20)),
                ('average_length', models.CharField(choices=[('LESS THAN ONE WEEK', 'Less than a week'), ('1 TO 2 WEEKS', '1-2 weeks'), ('3 TO 4 WEEKS', '3-4 weeks'), ('1 TO 3 MONTHS', '1-3 months'), ('3 TO 6 MONTHS', '3-6 months'), ('MORE THAN 6 MONTHS', '<6 months: I got no roots!')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
