# Generated by Django 2.2.5 on 2019-10-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_bracket',
            field=models.CharField(blank=True, choices=[('UNDER 12', 'Under 12 years old'), ('12-17', '12-17 years old'), ('18-24', '18-24 years old'), ('25-34', '25-34 years old'), ('35-44', '35-44 years old'), ('45-54', '45-54 years old'), ('55-64', '55-64 years old'), ('65-74', '65-74 years old'), ('OVER 75', '75 years or older')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='average_length',
            field=models.CharField(blank=True, choices=[('LESS THAN ONE WEEK', 'Less than a week'), ('1 TO 2 WEEKS', '1-2 weeks'), ('3 TO 4 WEEKS', '3-4 weeks'), ('1 TO 3 MONTHS', '1-3 months'), ('3 TO 6 MONTHS', '3-6 months'), ('MORE THAN 6 MONTHS', '<6 months: I got no roots!')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dom_travel',
            field=models.CharField(blank=True, choices=[('1 OR LESS', 'One trip or less'), ('1 TO 3', '1-3 trips'), ('4 TO 8', '4-8 trips'), ('8 TO 12', '8-12 trips'), ('12 OR MORE', '12 or more trips')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='glter',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='home_airport',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='int_travel',
            field=models.CharField(blank=True, choices=[('1 OR LESS', 'One trip or less'), ('1 TO 3', '1-3 trips'), ('4 TO 8', '4-8 trips'), ('8 TO 12', '8-12 trips'), ('12 OR MORE', '12 or more trips')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='travel_style',
            field=models.CharField(blank=True, choices=[('FOODIE', 'Foodie'), ('LUX', 'Lux'), ('BUDGET', 'Budget'), ('SOLO', 'Solo'), ('HOTEL', 'Hotel'), ('FAMILY', 'Family'), ('WORK', 'Work')], max_length=20, null=True),
        ),
    ]
