# Generated by Django 2.2.5 on 2019-10-26 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserProfiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='instagram_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tiktok_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='facebook_url',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
    ]
